name = "ReducedOrderModelCBFs"
uuid = "130db762-5431-4c7a-8f91-cf2a98ae57c6"
authors = ["Max Cohen <maxcohen@bu.edu>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
